export const data = [
  {
    id: 1,
    name: "Navjot",
    age: 24,
    city: "mohali",
    gender: "female",
    address: "71 sector Ajitnagar",
    phone: "+91 7973539880",
  },
  {
    id: 2,
    name: "Aman",
    age: 28,
    city: "chandigarh",
    gender: "female",
    address: "74 sector mohali",
    phone: "+91 7973539880",
  },
  {
    id: 3,
    name: "Dolbeer",
    age: 21,
    city: "zirakpur",
    gender: "male",
    address: "66 sector mohali",
    phone: "+91 7973539880",
  },
  {
    id: 4,
    name: "kajal",
    age: 28,
    city: "mohali",
    gender: "female",
    address: "71 sector Ajitnagar",
    phone: "+91 7973539880",
  },
  {
    id: 5,
    name: "kajal",
    age: 28,
    city: "mohali",
    gender: "female",
    address: "71 sector Ajitnagar",
    phone: "+91 7973539880",
  },
  {
    id: 6,
    name: "kajal",
    age: 28,
    city: "mohali",
    gender: "female",
    address: "71 sector Ajitnagar",
    phone: "+91 7973539880",
  },
];

export const columns = [
  { dataField: "name", caption: "Name" },
  { dataField: "age", caption: "Age" },
  { dataField: "address", caption: "Address" },
  { dataField: "city", caption: "City" },
  { dataField: "gender", caption: "Gender" },
  { dataField: "phone", caption: "PhoneNumber" },
];
export const usersData = [
  {
    id: 1,
    name: "Navjot",
    age: 24,
    isActive: true,
    joiningDate: "2024-01-10",
  },
  {
    id: 2,
    name: "Aman",
    age: 28,
    isActive: false,
    joiningDate: "2023-05-12",
  },
  {
    id: 3,
    name: "Parneet",
    age: 28,
    isActive: false,
    joiningDate: "2023-05-18",
  },
  {
    id: 4,
    name: "Amandeep",
    age: 28,
    isActive: false,
    joiningDate: "2023-05-12",
  },
];
